### ISSUE TITLE
Python 3.11 Support 

### ISSUE THREAD

**Issue by msfidelis** [Nixtla/statsforecast#424]
### Description

Python 3.11 has released at `2022-10-24` and statsforecast installation only works in versions  3.7,3.8,3.9 and 3.10.

I would like to know if there is interest and planning to release a new statsforecast version with latest Python Support. 

### Stack Trace

```sh
Collecting statsforecast
  Downloading statsforecast-1.5.0-py3-none-any.whl (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.0/100.0 kB 2.8 MB/s eta 0:00:00
Requirement already satisfied: matplotlib in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from statsforecast) (3.6.2)
Collecting numba>=0.55.0
  Downloading numba-0.56.4.tar.gz (2.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 11.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/ht/zw2nx83j6w387qgthkq66lg80000gn/T/pip-install-vbvlhmhx/numba_e3c79a729f0042b09f7642cc429f5c76/setup.py", line 51, in <module>
          _guard_py_ver()
        File "/private/var/folders/ht/zw2nx83j6w387qgthkq66lg80000gn/T/pip-install-vbvlhmhx/numba_e3c79a729f0042b09f7642cc429f5c76/setup.py", line 48, in _guard_py_ver
          raise RuntimeError(msg.format(cur_py, min_py, max_py))
      RuntimeError: Cannot install on Python version 3.11.1; only versions >=3.7,<3.11 are supported.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Congrats for your work.

**Comment by FedericoGarza** [comment]
hey @msfidelis! Yes! We are planning to support py3.11 soon. The numba team is about to release a [new compatible version](https://github.com/numba/numba/issues/8841). 🚀 Hopefully, right after that release we will be able to have a stable version. :)

**Comment by msfidelis** [comment]
Great news! We have an open PR about this topic.

https://github.com/Nixtla/statsforecast/pull/425

Thanks for the Follow Up 🚀🚀

**Comment by jmoralez** [comment]
Closing since numba now supports python 3.11 and we have CI jobs with that version.
