### ISSUE TITLE
Nonseasonal data error when forecasting with confidence levels

### ISSUE THREAD

**Issue by RashidBakirov** [Nixtla/statsforecast#605]
### What happened + What you expected to happen

I get "Nonseasonal data" error if I specify level argument in forecast function while using models with seasonality. It strangely works if this argument is not specified, not sure if this is expected behaviour. Would appreciate advice on how to solve this.

```
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-ee58f831-c85d-4dbb-b836-6dc5532a2831/lib/python3.10/site-packages/statsforecast/core.py", line 203, in forecast
    raise error
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-ee58f831-c85d-4dbb-b836-6dc5532a2831/lib/python3.10/site-packages/statsforecast/core.py", line 189, in forecast
    res_i = model.forecast(
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-ee58f831-c85d-4dbb-b836-6dc5532a2831/lib/python3.10/site-packages/statsforecast/models.py", line 644, in forecast
    mod = ets_f(y, m=self.season_length, model=self.model, damped=self.damped)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-ee58f831-c85d-4dbb-b836-6dc5532a2831/lib/python3.10/site-packages/statsforecast/ets.py", line 1204, in ets_f
    raise ValueError("Nonseasonal data")
ValueError: Nonseasonal data
"""

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
File <command-1204008486372607>:1
----> 1 forecasts_df = sf.forecast(h=18, level=[90])
      2 forecasts_df.head()

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-ee58f831-c85d-4dbb-b836-6dc5532a2831/lib/python3.10/site-packages/statsforecast/core.py:1486, in StatsForecast.forecast(self, h, df, X_df, level, fitted, sort_df)
   1476 def forecast(
   1477     self,
   1478     h: int,
   (...)
   1483     sort_df: bool = True,
   1484 ):
   1485     if self._is_native(df=df):
-> 1486         return super().forecast(
   1487             h=h, df=df, X_df=X_df, level=level, fitted=fitted, sort_df=sort_df
   1488         )
   1489     assert df is not None
   1490     with fa.engine_context(infer_by=[df]) as e:

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-ee58f831-c85d-4dbb-b836-6dc5532a2831/lib/python3.10/site-packages/statsforecast/core.py:751, in _StatsForecast.forecast(self, h, df, X_df, level, fitted, sort_df)
    741     res_fcsts = self.ga.forecast(
    742         models=self.models,
    743         h=h,
   (...)
    748         verbose=self.verbose,
    749     )
    750 else:
--> 751     res_fcsts = self._forecast_parallel(h=h, fitted=fitted, X=X, level=level)
    752 if fitted:
    753     self.fcst_fitted_values_ = res_fcsts["fitted"]

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-ee58f831-c85d-4dbb-b836-6dc5532a2831/lib/python3.10/site-packages/statsforecast/core.py:1024, in _StatsForecast._forecast_parallel(self, h, fitted, X, level)
   1012     future = executor.apply_async(
   1013         ga.forecast,
   1014         (
   (...)
   1021         ),
   1022     )
   1023     futures.append(future)
-> 1024 out = [f.get() for f in futures]
   1025 fcsts = [d["forecasts"] for d in out]
   1026 fcsts = np.vstack(fcsts)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-ee58f831-c85d-4dbb-b836-6dc5532a2831/lib/python3.10/site-packages/statsforecast/core.py:1024, in <listcomp>(.0)
   1012     future = executor.apply_async(
   1013         ga.forecast,
   1014         (
   (...)
   1021         ),
   1022     )
   1023     futures.append(future)
-> 1024 out = [f.get() for f in futures]
   1025 fcsts = [d["forecasts"] for d in out]
   1026 fcsts = np.vstack(fcsts)

File /usr/lib/python3.10/multiprocessing/pool.py:774, in ApplyResult.get(self, timeout)
    772     return self._value
    773 else:
--> 774     raise self._value

ValueError: Nonseasonal data
```
 

### Versions / Dependencies

python==3.10.6
statsmodels==0.13.2
pandas==1.4.4
numba==0.55.1
numpy==1.21.6

### Reproduction script

(can't include reproducible script because of private data)

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by callmesora** [comment]
Same error here :(

**Comment by RashidBakirov** [comment]
I have tried cleaning the data, getting rid of missing values and bringing it to the same horizon. Using levels still fails but with a different error message now:

```
TypeError: object of type 'int' has no len()
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-b9835afb-2e4b-40d0-8552-0ef7b211dceb/lib/python3.10/site-packages/statsforecast/core.py", line 156, in forecast
    fcsts, cuts, has_level_models = self._output_fcst(
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-b9835afb-2e4b-40d0-8552-0ef7b211dceb/lib/python3.10/site-packages/statsforecast/core.py", line 95, in _output_fcst
    cuts, has_level_models = self._get_cols(
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-b9835afb-2e4b-40d0-8552-0ef7b211dceb/lib/python3.10/site-packages/statsforecast/core.py", line 85, in _get_cols
    and len(level) > 0
TypeError: object of type 'int' has no len()
"""

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
File <command-1204008486372607>:1
----> 1 forecasts_df = sf.forecast(h=12,level=90)
      2 forecasts_df.head()

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-b9835afb-2e4b-40d0-8552-0ef7b211dceb/lib/python3.10/site-packages/statsforecast/core.py:1486, in StatsForecast.forecast(self, h, df, X_df, level, fitted, sort_df)
   1476 def forecast(
   1477     self,
   1478     h: int,
   (...)
   1483     sort_df: bool = True,
   1484 ):
   1485     if self._is_native(df=df):
-> 1486         return super().forecast(
   1487             h=h, df=df, X_df=X_df, level=level, fitted=fitted, sort_df=sort_df
   1488         )
   1489     assert df is not None
   1490     with fa.engine_context(infer_by=[df]) as e:

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-b9835afb-2e4b-40d0-8552-0ef7b211dceb/lib/python3.10/site-packages/statsforecast/core.py:751, in _StatsForecast.forecast(self, h, df, X_df, level, fitted, sort_df)
    741     res_fcsts = self.ga.forecast(
    742         models=self.models,
    743         h=h,
   (...)
    748         verbose=self.verbose,
    749     )
    750 else:
--> 751     res_fcsts = self._forecast_parallel(h=h, fitted=fitted, X=X, level=level)
    752 if fitted:
    753     self.fcst_fitted_values_ = res_fcsts["fitted"]

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-b9835afb-2e4b-40d0-8552-0ef7b211dceb/lib/python3.10/site-packages/statsforecast/core.py:1024, in _StatsForecast._forecast_parallel(self, h, fitted, X, level)
   1012     future = executor.apply_async(
   1013         ga.forecast,
   1014         (
   (...)
   1021         ),
   1022     )
   1023     futures.append(future)
-> 1024 out = [f.get() for f in futures]
   1025 fcsts = [d["forecasts"] for d in out]
   1026 fcsts = np.vstack(fcsts)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-b9835afb-2e4b-40d0-8552-0ef7b211dceb/lib/python3.10/site-packages/statsforecast/core.py:1024, in <listcomp>(.0)
   1012     future = executor.apply_async(
   1013         ga.forecast,
   1014         (
   (...)
   1021         ),
   1022     )
   1023     futures.append(future)
-> 1024 out = [f.get() for f in futures]
   1025 fcsts = [d["forecasts"] for d in out]
   1026 fcsts = np.vstack(fcsts)

File /usr/lib/python3.10/multiprocessing/pool.py:774, in ApplyResult.get(self, timeout)
    772     return self._value
    773 else:
--> 774     raise self._value

TypeError: object of type 'int' has no len()
```

**Comment by jmoralez** [comment]
Hey @RashidBakirov, level is expected to be a collection. Can you please try `level=[90]`? Also if you're able to reproduce this with some random data it'd be very useful for us to debug. Thanks!

**Comment by RashidBakirov** [comment]
> Hey @RashidBakirov, level is expected to be a collection. Can you please try `level=[90]`? Also if you're able to reproduce this with some random data it'd be very useful for us to debug. Thanks!

Thanks, this worked!
