### ISSUE TITLE
IndexError: list index out of range in StatsForecast with X_df

### ISSUE THREAD

**Issue by jbkix06** [Nixtla/statsforecast#737]
### What happened + What you expected to happen

When running  StatsForecast.Forecast in DataBricks using spak I get an IndexError (PythonException: 'IndexError: list index out of range'.)  The same code works if i roll StatsForecast back to 1.6.0

Full Traceback below:
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 8891.0 failed 4 times, most recent failure: Lost task 0.3 in stage 8891.0 (TID 358199) (100.80.0.66 executor 117): org.apache.spark.api.python.PythonException: 'IndexError: list index out of range'. Full traceback below:
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-8072b353-a499-44b1-af5a-4062d896f1eb/lib/python3.9/site-packages/fugue_spark/execution_engine.py", line 228, in _udf_pandas
    output_df = map_func(cursor, input_df)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-8072b353-a499-44b1-af5a-4062d896f1eb/lib/python3.9/site-packages/fugue/execution/execution_engine.py", line 1336, in run
    return self.func(_c, dfs)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-8072b353-a499-44b1-af5a-4062d896f1eb/lib/python3.9/site-packages/fugue/extensions/_builtins/processors.py", line 362, in run
    return self.transformer.transform(dfs)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-8072b353-a499-44b1-af5a-4062d896f1eb/lib/python3.9/site-packages/fugue/extensions/transformer/convert.py", line 449, in transform
    return self._wrapper.run(  # type: ignore
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-8072b353-a499-44b1-af5a-4062d896f1eb/lib/python3.9/site-packages/fugue/dataframe/function_wrapper.py", line 94, in run
    rt = self._func(**rargs)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-8072b353-a499-44b1-af5a-4062d896f1eb/lib/python3.9/site-packages/statsforecast/distributed/fugue.py", line 203, in _forecast_X
    _, result = self._forecast(
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-8072b353-a499-44b1-af5a-4062d896f1eb/lib/python3.9/site-packages/statsforecast/distributed/fugue.py", line 110, in _forecast
    result = model.forecast(
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-8072b353-a499-44b1-af5a-4062d896f1eb/lib/python3.9/site-packages/statsforecast/core.py", line 814, in forecast
    X, level = self._parse_X_level(h=h, X=X_df, level=level)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-8072b353-a499-44b1-af5a-4062d896f1eb/lib/python3.9/site-packages/statsforecast/core.py", line 653, in _parse_X_level
    first_col = [c for c in X.columns if c not in (self.id_col, self.time_col)][0]
IndexError: list index out of range

	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:685)
	at org.apache.spark.sql.execution.python.PythonArrowOutput$$anon$1.read(PythonArrowOutput.scala:118)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:638)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:491)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.sql.execution.collect.UnsafeRowBatchUtils$.encodeUnsafeRows(UnsafeRowBatchUtils.scala:82)
	at org.apache.spark.sql.execution.collect.Collector.$anonfun$processFunc$1(Collector.scala:208)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$3(ResultTask.scala:75)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$1(ResultTask.scala:75)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:55)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:179)
	at org.apache.spark.scheduler.Task.$anonfun$run$5(Task.scala:142)
	at com.databricks.unity.EmptyHandle$.runWithAndClose(UCSHandle.scala:125)
	at org.apache.spark.scheduler.Task.$anonfun$run$1(Task.scala:142)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.Task.run(Task.scala:97)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$13(Executor.scala:904)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1713)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:907)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:761)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:3386)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:3318)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:3309)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:3309)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1433)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1433)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1433)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3598)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3536)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3524)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:51)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$runJob$1(DAGScheduler.scala:1182)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:80)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:1170)
	at org.apache.spark.SparkContext.runJobInternal(SparkContext.scala:2750)
	at org.apache.spark.sql.execution.collect.Collector.$anonfun$runSparkJobs$1(Collector.scala:349)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:80)
	at org.apache.spark.sql.execution.collect.Collector.runSparkJobs(Collector.scala:293)
	at org.apache.spark.sql.execution.collect.Collector.collect(Collector.scala:377)
	at org.apache.spark.sql.execution.collect.Collector$.collect(Collector.scala:128)
	at org.apache.spark.sql.execution.collect.Collector$.collect(Collector.scala:135)
	at org.apache.spark.sql.execution.qrc.InternalRowFormat$.collect(cachedSparkResults.scala:122)
	at org.apache.spark.sql.execution.qrc.InternalRowFormat$.collect(cachedSparkResults.scala:110)
	at org.apache.spark.sql.execution.qrc.InternalRowFormat$.collect(cachedSparkResults.scala:92)
	at org.apache.spark.sql.execution.qrc.ResultCacheManager.$anonfun$computeResult$1(ResultCacheManager.scala:537)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:80)
	at org.apache.spark.sql.execution.qrc.ResultCacheManager.collectResult$1(ResultCacheManager.scala:529)
	at org.apache.spark.sql.execution.qrc.ResultCacheManager.$anonfun$computeResult$2(ResultCacheManager.scala:547)
	at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.$anonfun$withFinalPlanUpdate$1(AdaptiveSparkPlanExec.scala:629)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:80)
	at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.withFinalPlanUpdate(AdaptiveSparkPlanExec.scala:627)
	at org.apache.spark.sql.execution.qrc.ResultCacheManager.computeResult(ResultCacheManager.scala:547)
	at org.apache.spark.sql.execution.qrc.ResultCacheManager.$anonfun$getOrComputeResultInternal$1(ResultCacheManager.scala:402)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.execution.qrc.ResultCacheManager.getOrComputeResultInternal(ResultCacheManager.scala:395)
	at org.apache.spark.sql.execution.qrc.ResultCacheManager.getOrComputeResult(ResultCacheManager.scala:289)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeCollectResult$1(SparkPlan.scala:506)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:80)
	at org.apache.spark.sql.execution.SparkPlan.executeCollectResult(SparkPlan.scala:503)
	at org.apache.spark.sql.Dataset.collectResult(Dataset.scala:3458)
	at org.apache.spark.sql.Dataset.$anonfun$collectResult$1(Dataset.scala:3449)
	at org.apache.spark.sql.Dataset.$anonfun$withAction$3(Dataset.scala:4373)
	at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:809)
	at org.apache.spark.sql.Dataset.$anonfun$withAction$2(Dataset.scala:4371)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$8(SQLExecution.scala:233)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:417)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$1(SQLExecution.scala:178)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:1038)
	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:128)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:367)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:4371)
	at org.apache.spark.sql.Dataset.collectResult(Dataset.scala:3448)
	at com.databricks.backend.daemon.driver.OutputAggregator$.withOutputAggregation0(OutputAggregator.scala:267)
	at com.databricks.backend.daemon.driver.OutputAggregator$.withOutputAggregation(OutputAggregator.scala:101)
	at com.databricks.backend.daemon.driver.PythonDriverLocalBase.generateTableResult(PythonDriverLocalBase.scala:723)
	at com.databricks.backend.daemon.driver.JupyterDriverLocal.computeListResultsItem(JupyterDriverLocal.scala:844)
	at com.databricks.backend.daemon.driver.JupyterDriverLocal$JupyterEntryPoint.addCustomDisplayData(JupyterDriverLocal.scala:263)
	at sun.reflect.GeneratedMethodAccessor927.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:306)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:195)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:115)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.apache.spark.api.python.PythonException: 'IndexError: list index out of range'. Full traceback below:
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-8072b353-a499-44b1-af5a-4062d896f1eb/lib/python3.9/site-packages/fugue_spark/execution_engine.py", line 228, in _udf_pandas
    output_df = map_func(cursor, input_df)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-8072b353-a499-44b1-af5a-4062d896f1eb/lib/python3.9/site-packages/fugue/execution/execution_engine.py", line 1336, in run
    return self.func(_c, dfs)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-8072b353-a499-44b1-af5a-4062d896f1eb/lib/python3.9/site-packages/fugue/extensions/_builtins/processors.py", line 362, in run
    return self.transformer.transform(dfs)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-8072b353-a499-44b1-af5a-4062d896f1eb/lib/python3.9/site-packages/fugue/extensions/transformer/convert.py", line 449, in transform
    return self._wrapper.run(  # type: ignore
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-8072b353-a499-44b1-af5a-4062d896f1eb/lib/python3.9/site-packages/fugue/dataframe/function_wrapper.py", line 94, in run
    rt = self._func(**rargs)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-8072b353-a499-44b1-af5a-4062d896f1eb/lib/python3.9/site-packages/statsforecast/distributed/fugue.py", line 203, in _forecast_X
    _, result = self._forecast(
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-8072b353-a499-44b1-af5a-4062d896f1eb/lib/python3.9/site-packages/statsforecast/distributed/fugue.py", line 110, in _forecast
    result = model.forecast(
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-8072b353-a499-44b1-af5a-4062d896f1eb/lib/python3.9/site-packages/statsforecast/core.py", line 814, in forecast
    X, level = self._parse_X_level(h=h, X=X_df, level=level)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-8072b353-a499-44b1-af5a-4062d896f1eb/lib/python3.9/site-packages/statsforecast/core.py", line 653, in _parse_X_level
    first_col = [c for c in X.columns if c not in (self.id_col, self.time_col)][0]
IndexError: list index out of range

	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:685)
	at org.apache.spark.sql.execution.python.PythonArrowOutput$$anon$1.read(PythonArrowOutput.scala:118)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:638)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:491)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.sql.execution.collect.UnsafeRowBatchUtils$.encodeUnsafeRows(UnsafeRowBatchUtils.scala:82)
	at org.apache.spark.sql.execution.collect.Collector.$anonfun$processFunc$1(Collector.scala:208)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$3(ResultTask.scala:75)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$1(ResultTask.scala:75)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:55)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:179)
	at org.apache.spark.scheduler.Task.$anonfun$run$5(Task.scala:142)
	at com.databricks.unity.EmptyHandle$.runWithAndClose(UCSHandle.scala:125)
	at org.apache.spark.scheduler.Task.$anonfun$run$1(Task.scala:142)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.Task.run(Task.scala:97)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$13(Executor.scala:904)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1713)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:907)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:761)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more

### Versions / Dependencies

statsforecast==1.7.0

### Reproduction script

hist_df = forecast_df.filter(f.col('ds')<f.lit(test_start_date))
futr_df = forecast_df.filter(f.col('ds')>=f.lit(test_start_date)).drop('y')
fut_y = forecast_df.filter(f.col('ds')>=f.lit(test_start_date)).select('y')
#prediction_intervals = ConformalIntervals(h=88, n_windows=1)

models = [SeasonalNaive(season_length=7)]

sf = StatsForecast(
   models=models,
   freq='D',
   verbose=True,
   n_jobs=-1
)

predictions = sf.forecast(
   h=88,
   df= hist_df,
   X_df=futr_df,
   level=[90],
   #prediction_intervals=prediction_intervals,
)

display(predictions)

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by jmoralez** [comment]
Hey @jbkix06, thanks for using statsforecast and for the example. It seems that `futr_df` doesn't have extra columns (apart from the id and the time), which is causing that error. The `X_df` argument is used to provide future values of exogenous regressors, so if for example you used price in your training set you'd have to provide it for every id and time in the forecasting horizon using that argument. If you don't have any exogenous features then it's not needed. We'll work on adding more informative error messages, thanks for raising this!

**Comment by jmoralez** [comment]
Closing since it seems to have been solved.
