### ISSUE TITLE
Getting error when training AutoCES on covid deaths dataset from gluonts 

### ISSUE THREAD

**Issue by Mo-Abdelhameed** [Nixtla/statsforecast#811]
I am trying to fit an AutoCES model to the covid deaths dataset test but I get this exception: `Exception: no model able to be fitted`

I am using the following code 

```python
import pandas as pd
import numpy as np
from gluonts.dataset.repository.datasets import get_dataset
from gluonts.time_feature.seasonality import get_seasonality
from statsforecast.models import AutoCES
from statsforecast import StatsForecast


dataset = get_dataset("covid_deaths", regenerate=False)

# Access the train and test datasets
train_dataset = dataset.train
test_dataset = dataset.test


records = []
for entry in dataset.train:
    target_values = entry["target"]
    item_id = entry["item_id"] if "item_id" in entry else "unknown_item"
    start_date = entry["start"]
    if isinstance(start_date, pd.Period):
        start_date = start_date.to_timestamp()
    # Generate the date range for the target values
    dates = pd.date_range(
        start=start_date, periods=len(target_values), freq=dataset.metadata.freq
    )

    # Append records for each date-target pair along with the item_id
    for target, date in zip(target_values, dates):
        records.append({"y": target, "unique_id": item_id, "ds": date})

# Create a DataFrame from the records
df = pd.DataFrame(records)


season_length = get_seasonality(dataset.metadata.freq)
models = [
    AutoCES(season_length=season_length),
]

model = StatsForecast(
    models=models,
    freq=dataset.metadata.freq,
)

model.fit(df)
```
---

The passed data frame looks like this
<img width="335" alt="Screenshot 2024-04-09 at 5 27 18 PM" src="https://github.com/Nixtla/statsforecast/assets/73613367/7603b60b-4863-466f-9691-7e3429582015">

And this is the Traceback
```
Traceback (most recent call last):
  File "/Users/moo/Desktop/ReadyTensor/Models/Forecasting/nixtla/statistical_ensemble/test.py", line 47, in <module>
    model.fit(df)
  File "/Users/moo/Desktop/ReadyTensor/Models/Forecasting/nixtla/statistical_ensemble/.venv/lib/python3.11/site-packages/statsforecast/core.py", line 646, in fit
    self.fitted_ = self.ga.fit(
                   ^^^^^^^^^^^^
  File "/Users/moo/Desktop/ReadyTensor/Models/Forecasting/nixtla/statistical_ensemble/.venv/lib/python3.11/site-packages/statsforecast/core.py", line 65, in fit
    raise error
  File "/Users/moo/Desktop/ReadyTensor/Models/Forecasting/nixtla/statistical_ensemble/.venv/lib/python3.11/site-packages/statsforecast/core.py", line 59, in fit
    fm[i, i_model] = new_model.fit(y=y, X=X)
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moo/Desktop/ReadyTensor/Models/Forecasting/nixtla/statistical_ensemble/.venv/lib/python3.11/site-packages/statsforecast/models.py", line 963, in fit
    self.model_ = auto_ces(y, m=self.season_length, model=self.model)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moo/Desktop/ReadyTensor/Models/Forecasting/nixtla/statistical_ensemble/.venv/lib/python3.11/site-packages/statsforecast/ces.py", line 782, in auto_ces
    raise Exception("no model able to be fitted")
Exception: no model able to be fitted
```

Can someone please help with this error?

Thanks.

**Comment by obiii** [comment]
Hi,

I am facing the same problem and in my case I don't  have any constant columns. Can someone help please?

**Comment by jmoralez** [comment]
@obiii can you please provide a small reproducible example of your error? The problem here is that for some series all values are the same, it doesn't have to be the full column, just all the values for a specific id.

**Comment by obiii** [comment]
> @obiii can you please provide a small reproducible example of your error? The problem here is that for some series all values are the same, it doesn't have to be the full column, just all the values for a specific id.

Hi,

I am following exactly this: https://nixtlaverse.nixtla.io/statsforecast/docs/getting-started/getting_started_complete.html but with my own data.

I will check if any series (unique_id) is constant, this is highly improbable though!
