### ISSUE TITLE
StatsForecast: No model able to be fitted

### ISSUE THREAD

**Issue by obiii** [Nixtla/statsforecast#816]
### What happened + What you expected to happen

I am training a a collection of models on my data containing only 'ds, unique_id, y' columns.

I am getting this trace:

multiprocessing.pool.RemoteTraceback: 
```
"""
Traceback (most recent call last):
  File "/opt/miniconda/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/opt/miniconda/lib/python3.10/site-packages/statsforecast/core.py", line 65, in fit
    raise error
  File "/opt/miniconda/lib/python3.10/site-packages/statsforecast/core.py", line 59, in fit
    fm[i, i_model] = new_model.fit(y=y, X=X)
  File "/opt/miniconda/lib/python3.10/site-packages/statsforecast/models.py", line 963, in fit
    self.model_ = auto_ces(y, m=self.season_length, model=self.model)
  File "/opt/miniconda/lib/python3.10/site-packages/statsforecast/ces.py", line 782, in auto_ces
    raise Exception("no model able to be fitted")
Exception: no model able to be fitted
"""
```

### Versions / Dependencies

statsforecast version: 1.7.3
Python: 3.11

### Reproduction script

The models list I am using is:

```
self.models = [
            AutoARIMA(season_length=30, nmodels=90, allowdrift=True),
            AutoCES(season_length=30),
            AutoETS(season_length=30),
            HoltWinters(season_length=30),
            MSTL(season_length=30, trend_forecaster=AutoARIMA(), alias="MSTL-ARIMA"),
            MSTL(season_length=30),
            AutoTheta(season_length=30),
            DOT(season_length=30),
            RandomWalkWithDrift(),
]
elf.dc_models = StatsForecast(
                    models=self.models,
                    freq="D",
                    n_jobs=-1,
)
self.dc_models.fit(data)
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by jmoralez** [comment]
Closing in favor of #811, which has a reproducible example.
